version: '3'
services:
  spark:
    image: my_jupyter_image
    container_name: devAcoes
    ports:
      - '8888:8888'
      - '8080:8080'
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/usr/local/spark/python/lib/py4j-0.10.9-src.zip:/usr/local/spark/python
      - PYSPARK_PYTHON=python3
      - WAREHOUSE_TYPE=jdbc
      - WAREHOUSE_URI=jdbc:postgresql://dw_acoes:5432/dw
      - WAREHOUSE_DATABASE=dw
      - WAREHOUSE_USER=dw
      - WAREHOUSE_PASSWORD=dw
    volumes:
      - 'C:/Users/duani/OneDrive/Github/Projetos/projeto_acoes/conf:/usr/local/spark/conf'
      - 'C:/Users/duani/OneDrive/Github/Projetos/projeto_acoes/data:/spark/home'
      - 'C:/Users/duani/OneDrive/Github/Projetos/projeto_acoes/notebook:/home/jovyan/work'
      - 'C:/Users/duani/OneDrive/Github/Projetos/projeto_acoes/driver/jdbc:/usr/local/etc/jdbc'

  postgres:
    image: postgres
    container_name: dw_acoes
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=dw
      - POSTGRES_USER=dw
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'C:/Users/duani/OneDrive/Github/Projetos/projeto_acoes/data/dw:/var/lib/postgresql/data'